### ISSUE TITLE
模型推理

### ISSUE THREAD

**Issue by world2025** [Lornatang/SRDenseNet-PyTorch#1]
你好，非常感谢你的开源，学习一波了，我想问下根据你给的如何推理一张图片呀，好像只有测试评估指标的，还有就是你给的训练和测试的那些改动点是针对哪个文件呢，我看了下train.py也不太像，哈哈

**Comment by Lornatang** [comment]
推理一张图直接在test.py里面改就好了

**Comment by world2025** [comment]
@Lornatang  test.py? 是不是在我盲区啊

**Comment by Lornatang** [comment]
抱歉，validate.py中~~

**Comment by Lornatang** [comment]
将lr_path改掉

**Comment by world2025** [comment]
@Lornatang 好的，谢谢
